### ISSUE TITLE
Installation demo

### ISSUE THREAD

**Issue by Gldkslfmsd** [lefterav/qegui#1]
Hello,

I would like to review this tool, but I have issues with installation. Since I'm new to Django, I don't know, how to start using it, and your paper or readme don't specify it. Can you please upgrade it with the commands to install and run it?

Thanks!

**Comment by lefterav** [comment]
Hi, the installation instructions have been added. They are still very poor, please re-open the ticket and reply here in case more details are needed.

**Comment by Gldkslfmsd** [comment]
Thanks! I will do it.


čt 6. 9. 2018 v 15:40 odesílatel Eleftherios Avramidis <
notifications@github.com> napsal:

**Comment by Gldkslfmsd** [comment]
Hello,

- what do you mean by this?

> 5) start the development webserver

I skip this step.

- step 6 should be `python3 manage.py runserver [PORT]`, startserver doesn't work.

> (note: ignore the Model field, different QE models are not yet supported by the system).

I don't see the Model field anywhere

When I create a document and open it through a browser, this error appears:

http://dpaste.com/2V6AQH1

**Comment by lefterav** [comment]
Thanks for your feedback
-  Step 5 should indeed not be there. 
- indeed, step 6 should use `runserver`. 
- the Model field is a dropdown menu at the "Document Evaluation" at the administration panel. You won't need to use this for the first steps. I will make it clear at the doc

**Comment by lefterav** [comment]
The issue with the undeclared variable was also fixed.
